name: task_manager
description: TaskManagerSystem
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  injectable: ^2.3.1
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
        - asset: assets/fonts/inter/Inter-Medium.ttf
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Light.ttf

  assets:
    - assets/icons/